# Generated by Django 4.2.30 on 2026-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "Access Request"),
                            ("donation", "Device Donation"),
                            ("partnership", "Partnership"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(max_length=3000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="requests_ap_created_175774_idx"
                    ),
                    models.Index(
                        fields=["status"], name="requests_ap_status_9b7335_idx"
                    ),
                    models.Index(fields=["email"], name="requests_ap_email_83dd75_idx"),
                ],
            },
        ),
    ]
